# Generated by Django 4.1.5 on 2023-04-13 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nickname", models.CharField(max_length=128)),
                (
                    "studentnumber",
                    models.CharField(default="", max_length=128, null=True),
                ),
                ("major", models.CharField(max_length=128)),
                ("interest", models.CharField(max_length=128)),
                (
                    "image",
                    models.ImageField(default="default.png", upload_to="profile/"),
                ),
            ],
        ),
    ]
