# Generated by Django 4.1.5 on 2023-02-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_delete_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="subject",
            new_name="subjects",
        ),
    ]
