# Generated by Django 4.1.5 on 2023-02-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_rename_subject_profile_subjects"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="position",
            new_name="interest",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="subjects",
            new_name="major",
        ),
        migrations.AddField(
            model_name="profile",
            name="studentnumber",
            field=models.CharField(default="", max_length=128, null=True),
        ),
    ]
