# Generated by Django 4.1.5 on 2023-04-13 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="bookPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="책 제목")),
                ("writer", models.CharField(max_length=100, verbose_name="책 작가")),
                ("publisher", models.CharField(max_length=100, verbose_name="출판사")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일자"),
                ),
                ("content", models.TextField(verbose_name="책 설명")),
                ("hits", models.PositiveIntegerField(default=0, verbose_name="조회수")),
                ("image", models.ImageField(default="default.png", upload_to="post/")),
                ("sell_price", models.IntegerField(default=0, verbose_name="대여 금액")),
                ("summary", models.TextField(default="", verbose_name="책 요약")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("very good", "매우 좋음"),
                            ("good", "좋음"),
                            ("bad", "나쁨"),
                            ("soso", "보통"),
                            ("not bad", "나쁘지 않음"),
                        ],
                        max_length=100,
                        verbose_name="책 상태",
                    ),
                ),
                (
                    "state_image",
                    models.ImageField(default="default.png", upload_to="post/"),
                ),
                ("tags_list", models.CharField(max_length=100)),
                ("like", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.profile",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="태그",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "headcount",
                    models.PositiveIntegerField(default=0, verbose_name="스터디 인원"),
                ),
                ("study_period", models.DurationField()),
                (
                    "book_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study",
                        to="home.bookpost",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "study",
            },
        ),
        migrations.CreateModel(
            name="bookComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("comment", models.TextField()),
                (
                    "book_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="home.bookpost",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "book_comment",
            },
        ),
    ]
