# Generated by Django 4.1.5 on 2023-02-16 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0005_auto_20220424_2025"),
        ("home", "0003_booksearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookpost",
            name="sell_price",
            field=models.IntegerField(default=0, verbose_name="대여 금액"),
        ),
        migrations.AlterField(
            model_name="bookcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="bookpost",
            name="author",
            field=models.CharField(max_length=100, verbose_name="책 작가"),
        ),
        migrations.AlterField(
            model_name="bookpost",
            name="content",
            field=models.TextField(verbose_name="책 설명"),
        ),
        migrations.AlterField(
            model_name="bookpost",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성 일자"),
        ),
        migrations.AlterField(
            model_name="bookpost",
            name="hits",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
        migrations.AlterField(
            model_name="bookpost",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="bookpost",
            name="publisher",
            field=models.CharField(max_length=100, verbose_name="출판사"),
        ),
        migrations.AlterField(
            model_name="bookpost",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="태그",
            ),
        ),
        migrations.AlterField(
            model_name="bookpost",
            name="title",
            field=models.CharField(max_length=100, verbose_name="책 제목"),
        ),
        migrations.AlterField(
            model_name="bookpost",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
    ]
